### ISSUE TITLE
issue in the navigation with the file prompt

### ISSUE THREAD

**Issue by sajadmowlaei** [Battlehub0x/RTE_Docs#45] opened 2022-08-12 09:11 UTC
If you click "load" you normally start within the project folder structure. However, in our case, our scenarios are located at /local_storage/simulation-database. If we want to navigate to that folder using the dialog (clicking "..." several times), once we reach "/", the scenario viewer will throw an error. Pasting the complete link manually below the dialog, works fine

https://user-images.githubusercontent.com/20297033/184323141-08d2be34-6749-4049-8a47-497666f062d2.mp4

![Selection_432](https://user-images.githubusercontent.com/20297033/184323313-ff3bad5f-6c18-4e94-8e92-45f96a6b5677.png)
.

**Comment by Battlehub0x** [comment] 2024-06-27 10:01
no wonder after 2 years the video link doesn't work and I can't reproduce the problem. I will close it for now, please open it again if the bug is still present or has any significance after all these years.

**Closed by Battlehub0x** 2024-06-27 10:01 UTC
